import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'chrome', headless: true });
const p = await (await b.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
await p.goto('https://qaid-bay.vercel.app/login');
await p.screenshot({ path: 'raw/x-login.png' });
await p.getByRole('button', { name: /Ahmed/i }).click();
await p.waitForURL(/board/, { timeout: 60000 });
await p.waitForTimeout(8000);
await p.screenshot({ path: 'raw/x-board.png' });
const links = await p.$$eval('a[href^="/board/"]', (as) => as.map((a) => a.getAttribute('href') + ' ' + a.innerText.replace(/\n/g, ' | ')));
console.log(links.join('\n'));
await b.close();
